### PR TITLE
cut down log spam resulting from record conversion failures

### PR DESCRIPTION
**Pull request by michae1T**
we are greatly under reporting these issues and often outright
suppressing.  the issue is we use cloudwatch logging which has
maximum log line limit.  most lines were then split into two log
elements.  the cloudwatch alarm is based on a json logs filter
pattern { $.level="ERROR" } - since the log line is split in two
it can not be parsed as json so is not considered an error.

the log line in question repeated the raw message and error 3 times.
I have moved the raw message to debug and refactored the pattern
where new *Exception or log is applied redundantly to
("text" + cause.getMessage, cause).

### CODE REVIEW

**Comment by andreyk0** [comment]
👍  LGTM, @gheine wdyt?

**Comment by michae1T** [comment]
the default behaviour for printing a exception:
```
new Exception("outer", new Exception("inner")).printStackTrace    
java.lang.Exception: outer
        at $line7.$read$$iw$$iw$.<init>(<console>:12)
....skipped...
Caused by: java.lang.Exception: inner
        ... 28 more
```

logging depends on the logging config but it is safe to say most print the message and exceptions full stack trace if available.

**Comment by michae1T** [comment]
@gheine

**Comment by andreyk0** [comment]
👍  I think it should be fine. If @gheine agrees - let's merge / release an updated version.

**Comment by gheine** [comment]
Yeah go for it!

**Pull request merged**
